### ISSUE TITLE
test error in ExteriorCalculus.jl

### ISSUE THREAD

**Issue by slwu89** [AlgebraicJulia/CombinatorialSpaces.jl#36]
Hi all,

I'm trying to run tests/precompile this package and getting an error that the type `AdditiveCategory` as used in [here in ExteriorCalculus.jl](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/d9e3c383d875f6b2fc3800eaca901ed331010a1e/src/ExteriorCalculus.jl#L26) is not defined. I tried adding `AdditiveCategory` to the import list from `Catlab.Theories` but the error persisted.

**Comment by epatters** [comment]
What versions of Catlab and CombinatorialSpaces are you using?

**Comment by slwu89** [comment]
It was a version issue on my end. I was on Julia 1.5.2; CombinatorialSpaces specifics `Catlab = "0.11, 0.12"` are compatible but I guess the package manager installed Catlab v0.11.2 which was the last one compatible with Julia 1.5.2, hence the issue. On Julia 1.6.2 and Catlab v0.12.7 there's no problem.

**Comment by epatters** [comment]
OK, great. I guess I need to drop the Catlab v0.11 compatibility on this repo.
