### ISSUE TITLE
Uninitialized memory should not be depended on

### ISSUE THREAD

**Issue by olynch** [AlgebraicJulia/CombinatorialSpaces.jl#55]
With the new VecMaps refactor, we ran into a bug where previously a vector of booleans had just been used without initialization, and now this errors because accessing something uninitialized now returns nothing instead of something random.

After `copy_parts!`, the orientation array is uninitialized: https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/8480caa25baf7fae18478ab45410417cbbb6af1e/src/DiscreteExteriorCalculus.jl#L340, and then this is accessed here: https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/8480caa25baf7fae18478ab45410417cbbb6af1e/src/DiscreteExteriorCalculus.jl#L178.

The error in action: https://github.com/AlgebraicJulia/Catlab.jl/actions/runs/3624910884/jobs/6112385806

**Comment by lukem12345** [comment]
This was closed a while back by PR #56
