### ISSUE TITLE
Preallocation is interfering with autodiff

### ISSUE THREAD

**Issue by jpfairbanks** [AlgebraicJulia/CombinatorialSpaces.jl#69]
This function call is preallocating memory for the result, but this creates a convert to Float64 which fails for dual numbers. 

https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/a5553f4eace107f11bb6f667e6a02b582e5bcf9f/src/DiscreteExteriorCalculus.jl#L488

**Comment by lukem12345** [comment]
I dont think this sharp operator is being used in any examples or docs. There is a sharp matrix which is used in Decapodes

**Comment by jpfairbanks** [comment]
Ok great, we should use the matrix form for everything we can for GPUcapodes and Autodiff compat.
