### ISSUE TITLE
Infinite recursion calling loadmesh with a non AbstractMeshKey

### ISSUE THREAD

**Issue by quffaro** [AlgebraicJulia/CombinatorialSpaces.jl#72]
```
dset = DeltaSet1D()
add_vertices!(dset, 1)
dset |> loadmesh
```
This code will produce an error
```
Stacktrace:
     [1] loadmesh(s::DeltaSet1D, subdivision::Circumcenter)
       @ CombinatorialSpaces.Meshes ~/.julia/packages/CombinatorialSpaces/Wg7wx/src/Meshes.jl:74--- the last 1 lines are repeated 79982 more times ---
```

This occurs because loadmesh will call `subdivide_duals!(loadmesh(s), subdivision)`, and iterate.

I imagine there should be some way to eyeball whether this will recurse. I'm willing to assign this to myself.

**Comment by lukem12345** [comment]
Hi, which version of `loadmesh` is this calling? Can you please do `@which`? This function is not meant to be used this way.

**Comment by quffaro** [comment]
It's calling it here:
```
loadmesh(s)
     @ CombinatorialSpaces.Meshes ~/.julia/packages/CombinatorialSpaces/Wg7wx/src/Meshes.jl:74
```

**Comment by lukem12345** [comment]
Ok. It seems that there are two issues here. The typing on `loadmesh` should not allow this usage.

**Comment by quffaro** [comment]
Is it possible to distinguish at the type level "bad" objects from "good" ones so we could just overload `loadmesh`, or should there be code which checks for recursive badness (and throws an error?)?

**Comment by jpfairbanks** [comment]
It is this fallback method [here](https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/c8def89a5664003f390494fcbf5ffd5c5c9f7c55/src/Meshes.jl#L74).

This should have a generic type like `AbstractMeshIdentifier` that has concrete subtypes for all our existing meshes so that the fallback method isn't defined for `Any`.

**Comment by lukem12345** [comment]
Yes this should subtype `AbstractMeshKey`. The name "load" was originally chosen because we were literally loading a mesh from a zip file (i.e. Artifacts). What Matt wants is a helper function that takes a primal mesh, creates a dual mesh, and subdivides it.

**Comment by lukem12345** [comment]
But currently `EmbeddedDeltaDualComplex2D` already does this for a given `EmbeddedDeltaSet2D`. It just doesn't subdivide it in the same step. We could just do that, subdividing either Circumcentrically, Barycentrically, or None. And pick either circum. or bary. as default.

**Comment by lukem12345** [comment]
But currently `EmbeddedDeltaDualComplex2D` already does this for a given `EmbeddedDeltaSet2D`. It just doesn't subdivide it in the same step. We could just do that, subdividing either Circumcentrically, Barycentrically, or None. And pick either circum. or bary. as default.

**Comment by lukem12345** [comment]
@quffaro Please add minimal reproducible code that demonstrates this behavior by calling `EmbeddedDeltaDualComplex1D` and `subdivide_duals!`, not using the `loadmesh` function.

**Comment by quffaro** [comment]
Affirmative!
```
Point3D = GeometryBasics.Point{Float64}
primal=EmbeddedDeltaSet1D{Bool, Point3D}()
add_vertices!(primal, 5, point=[Point3D(i, i^2, 0) for i in -2:2])
add_edges!(primal, 1:4, 2:5, edge_orientation=true)

ds=EmbeddedDeltaDualComplex1D{Bool, Float64, Point3D}(primal)
subdivide_duals!(ds, Barycenter()) 

dss = copy(ds)
subdivide_duals!(dss, Barycenter())

dss==ds
```
