### ISSUE TITLE
Add Doc Page for Extensions

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/CombinatorialSpaces.jl#80]
Added docstrings but not sure as of yet how to have extensions be autodocumentated. I say we turn this into an issue for later.

_Originally posted by @GeorgeR227 in https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/pull/75#discussion_r1588414340_

**Comment by jpfairbanks** [comment]
This page is also missing the docs: https://algebraicjulia.github.io/CombinatorialSpaces.jl/dev/fast_dec/

**Comment by lukem12345** [comment]
This should be addressed by the most recent PR. I will of course double check when the action finishes

**Comment by jpfairbanks** [comment]
It looks like the docs for meshes are missing the plots on this page https://algebraicjulia.github.io/CombinatorialSpaces.jl/dev/meshes/

**Comment by lukem12345** [comment]
Closed by
81176312dd884566272229cdc6e0dd6959d63659
5a42700bc59f7c448a9699bc60bde99fc2f6343b
7354e5bf6cfdfa653011548bc39cb543d6bb06d4
