### ISSUE TITLE
Remove cu_wedge exports

### ISSUE THREAD

**Issue by GeorgeR227** [AlgebraicJulia/CombinatorialSpaces.jl#81]
https://github.com/AlgebraicJulia/CombinatorialSpaces.jl/blob/98edd592dac7ec74b4107df1c34fc4261dabf81b/src/FastDEC.jl#L12-L17

The exports on line 17 are no longer needed since the calling of CUDA wedge products has been changed to dispatch from regular dec wedge products.

**Comment by lukem12345** [comment]
In the PR that closes this issue, a doc string for the `FastDEC` module should be added. This will help clarify which functions are exported and why.

**Comment by GeorgeR227** [comment]
I'm running the tests now but I don't expect any problems.

**Comment by lukem12345** [comment]
@GeorgeR227 Do you have any updates on those CUDA tests?

**Comment by GeorgeR227** [comment]
All tests passed.

**Comment by lukem12345** [comment]
OK, make a PR and request review and we can merge.
